name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
    - name: Build Wexflow.Server.csproj
      run: dotnet build src/dotnet-core/Wexflow.Server/Wexflow.Server.csproj --configuration Release
    - name: Build WexFlow.Client.csproj
      run: dotnet build src/dotnet-core/Client/WexFlow.Client/WexFlow.Client.csproj --configuration Release
    - name: Build Wexflow.RabbitMQ.Client.csproj
      run: dotnet build src/dotnet-core/Wexflow.RabbitMQ.Client/Wexflow.RabbitMQ.Client.csproj --configuration Release
    - name: Build Wexflow.Clients.CommandLine.csproj
      run: dotnet build src/dotnet-core/Wexflow.Clients.CommandLine/Wexflow.Clients.CommandLine.csproj --configuration Release
    - name: Build Wexflow.Scripts.LiteDB.csproj
      run: dotnet build src/dotnet-core/Wexflow.Scripts.LiteDB/Wexflow.Scripts.LiteDB.csproj --configuration Release
    - name: Build Wexflow.Scripts.MongoDB.csproj
      run: dotnet build src/dotnet-core/Wexflow.Scripts.MongoDB/Wexflow.Scripts.MongoDB.csproj --configuration Release
    - name: Build Wexflow.DotnetCore.Tests.csproj
      run: dotnet build tests/dotnet-core/Wexflow.DotnetCore.Tests/Wexflow.DotnetCore.Tests.csproj --configuration Release
         
